# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af231b985a49b794fc49b7e6ee29c08544cf353e3cefb7805008e7eb9347604cdcdefb9023c186a17bb996324f43496d8f3fbf9a6ac53a93216e3ced514b886a

test:
  secret_key_base: c6c3e7fce2deb89a97fc8ae10ed6d165f90d4b41a47ab2a62cff8fcc170eca851e949ed59776049935d17f937611b2fdb3d81b8aa2fa1c427dc39428ffb97326

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
